---
- name: jenkins_role_based_strategy
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: '/usr/bin/python3'
    when: ansible_os_family == "Debian"

  pre_tasks:
    - include_tasks: java-8.yml

    - include_tasks: java-11.yml
      when:
        - ansible_distribution == 'Debian'
        - ansible_distribution_major_version == '10'

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
      jenkins_plugins:
        - github-oauth

    - role: binbash_inc.ansible_role_jenkins_github_oauth
      jenkins_github_oauth_client_id: "your-github-oauth-client-id"
      jenkins_github_oauth_client_secret: "your-github-oauth-client-secret"

  post_tasks:
    - name: Check if Jenkins is running.
      uri:
        url: "http://127.0.0.1:8080/"
